# Generated by Django 4.2.7 on 2023-11-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_description', models.CharField(max_length=500)),
                ('product_quantity', models.PositiveIntegerField(null=True)),
                ('product_price', models.FloatField(null=True)),
                ('product_sales', models.FloatField(null=True)),
            ],
        ),
    ]
